[tools]
node = "latest"
lua = ["5.1", "latest"]
usage = "latest"
go = "latest"
uv = "latest"
bun = "latest"
rust = "nightly"

[settings]
experimental = true
env_file = ".env"

trusted_config_paths = ['~/dev']
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
ruby_build_opts = "--with-gcc='gcc -std=gnu17'"
