monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "~bluez_card.*"
      }
    ]
    actions = {
      update-props = {
        # bluez5.a2dp.ldac.quality = "hq"
        bluez5.a2dp.ldac.quality = "auto"
      }
    }
  }
]
