monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_00_1f.3.analog-stereo"
      }
    ],
    actions = {
      update-props = {
        priority.driver = 1010
        priority.session = 1010
      }
    }
  },
  {
    matches = [
      {
        node.name = "alsa_output.usb-MOTU_M2_M20000023407-00.Direct__Direct__sink"
      }
    ],
    actions = {
      update-props = {
        priority.driver = 1020
        priority.session = 1020
      }
    }
  },
  {
    matches = [
      {
        node.name = "bluez_output.AC_80_0A_E8_27_9A.1"
      }
    ],
    actions = {
      update-props = {
        priority.driver = 1030
        priority.session = 1030
      }
    }
  }
]
