hwdec=auto
#osd-msg1=${playback-time/full} / ${duration} (${percent-pos}%)\nframe: ${estimated-frame-number} / ${estimated-frame-count}
screenshot-format=png
screenshot-template="%F - [%P] (%#01n)"
# cache-on-disk=yes
# cache=yes
# keep-open=yes

vo=gpu-next
gpu-api=opengl
# profile=fast
# sigmoid-upscaling=yes
# opengl-glfinish=yes
# force-window=yes
# video-sync=display-resample

save-position-on-quit=yes
