--ozone-platform-hint=auto
--enable-features=AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoEncoder,TouchpadOverscrollHistoryNavigation
--disable-features=ExtensionManifestV2Unsupported,ExtensionManifestV2Disabled
# --disable-smooth-scrolling
# --enable-gpu-compositing
# --enable-gpu-rasterization
# --enable-native-gpu-memory-buffers
# --enable-oop-rasterization
# --canvas-oop-rasterization
# --enable-raw-draw
# --enable-zero-copy
# --ignore-gpu-blocklist
# --disable-gpu-driver-bug-workarounds

# --enable-spatial-navigation
# --gtk-version=4
# --use-vulkan
