--ozone-platform-hint=auto
# --enable-features=WaylandWindowDecorations,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoEncoder,TouchpadOverscrollHistoryNavigation,PlatformHEVCDecoderSupport,CanvasOopRasterization
--enable-features=WaylandWindowDecorations,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoEncoder,TouchpadOverscrollHistoryNavigation,PlatformHEVCDecoderSupport
# --disable-smooth-scrolling

# --enable-gpu-compositing
# --enable-gpu-rasterization
# --enable-native-gpu-memory-buffers
# --enable-oop-rasterization
# --canvas-oop-rasterization
# --enable-raw-draw
# --enable-zero-copy
# --ignore-gpu-blocklist
# --disable-gpu-driver-bug-workarounds

--gtk-version=4
