local opt = vim.opt
opt.number = true
opt.relativenumber = true
opt.mouse = "a"
opt.cursorline = true
opt.title = true
opt.timeoutlen = 1000
opt.ttimeoutlen = 10
opt.splitbelow = true
opt.splitright = true
opt.laststatus = 3
opt.ignorecase = true
opt.smartcase = true
opt.signcolumn = "yes"
opt.scrolloff = 8
opt.undofile = true
-- opt.clipboard = 'unnamedplus'
opt.inccommand = "split"
opt.formatoptions = opt.formatoptions - "o"
opt.termguicolors = true
opt.expandtab = true
opt.shiftwidth = 2
opt.foldenable = false

local g = vim.g
g.mapleader = " "
g.user42 = "bvan-den"
g.mail42 = "bvan-den@student.codam.nl"
